# fly.toml app configuration file generated for events-app-server on 2023-06-07T18:53:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "events-app-server"
primary_region = "mad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
